### ISSUE TITLE
Not in the npm registry.

### ISSUE THREAD

**Issue by ghost** [robin4a4/jSimple#1]
Hey, I would love to play around with jSimple, however it doesn't seem to be in the npm registry yet.

Thankyou,
Jayman.

**Comment by robin4a4** [comment]
Hi ! I just published the three packages. I also added some docs in each packages as well as some basic examples that you can find [here](jsimple.marillia.io). Keep in mind that these apis are just a fun experiment and exploration of javascript internals !
